"""add middle name column to users table

Revision ID: 79603443e6b3
Revises: bb27d3ec7121
Create Date: 2025-06-11 09:28:02.225360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79603443e6b3'
down_revision = 'bb27d3ec7121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
